/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.gui;

/**
 *
 * @author TOSHIBAP55W
 */
public class VentanaOfertasEgresados extends javax.swing.JFrame {

    /**
     * Creates new form VentanaOfertasEgresados
     */
    public VentanaOfertasEgresados() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListOfertas = new javax.swing.JList();
        jLTitulo2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTARequerimientosOfert = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTFAreaConocimientoOfert = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTFSalarioOfert = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTFCiudadOfert = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTFAperturaOfert = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTADescripcionOfert = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAResumenOfert = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jTFCargoOfert = new javax.swing.JTextField();
        jBInicio = new javax.swing.JButton();
        jBAplicarOferta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ofertas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo1.setText("OFERTAS LABORALES");
        getContentPane().add(jLTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jScrollPane1.setViewportView(jListOfertas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 231, 278));

        jLTitulo2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo2.setText("Ofertas:");
        getContentPane().add(jLTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jTARequerimientosOfert.setColumns(20);
        jTARequerimientosOfert.setRows(5);
        jScrollPane2.setViewportView(jTARequerimientosOfert);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 310, 110));

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Requerimientos de la oferta:");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Apertura de la oferta:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, -1, -1));
        getContentPane().add(jTFAreaConocimientoOfert, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 310, 40));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Ciudad de la oferta:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, -1, -1));
        getContentPane().add(jTFSalarioOfert, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 310, 40));

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Cargo a Ofrecer:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, -1, -1));
        getContentPane().add(jTFCiudadOfert, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 310, 40));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Area de Conocimiento:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Salario:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));
        getContentPane().add(jTFAperturaOfert, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 630, 310, 40));

        jTADescripcionOfert.setColumns(20);
        jTADescripcionOfert.setRows(5);
        jScrollPane4.setViewportView(jTADescripcionOfert);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 310, 160));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Descripcion de la Oferta:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jTAResumenOfert.setColumns(20);
        jTAResumenOfert.setRows(5);
        jScrollPane3.setViewportView(jTAResumenOfert);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 310, 160));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Resumen:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, -1, -1));
        getContentPane().add(jTFCargoOfert, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, 310, 40));

        jBInicio.setBackground(new java.awt.Color(255, 255, 255));
        jBInicio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jBInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-inicio.jpg"))); // NOI18N
        jBInicio.setText("INICIO");
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jBInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 140, 60));

        jBAplicarOferta.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jBAplicarOferta.setForeground(new java.awt.Color(255, 0, 0));
        jBAplicarOferta.setText("APLICAR OFERTA");
        jBAplicarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAplicarOfertaActionPerformed(evt);
            }
        });
        getContentPane().add(jBAplicarOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 720, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1150, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        VentanaPrincipal principal = new VentanaPrincipal(0);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBInicioActionPerformed

    private void jBAplicarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAplicarOfertaActionPerformed
        VentanaPrincipal principal = new VentanaPrincipal(0);
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBAplicarOfertaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        VentanaPrincipal principal = new VentanaPrincipal(0);
        this.dispose();
        principal.setVisible(true);
       
    }//GEN-LAST:event_formWindowClosing

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAplicarOferta;
    private javax.swing.JButton jBInicio;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JLabel jLTitulo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JList<String> jListOfertas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTADescripcionOfert;
    private javax.swing.JTextArea jTARequerimientosOfert;
    private javax.swing.JTextArea jTAResumenOfert;
    private javax.swing.JTextField jTFAperturaOfert;
    private javax.swing.JTextField jTFAreaConocimientoOfert;
    private javax.swing.JTextField jTFCargoOfert;
    private javax.swing.JTextField jTFCiudadOfert;
    private javax.swing.JTextField jTFSalarioOfert;
    // End of variables declaration//GEN-END:variables
}
