/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.gui;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.controladores.ControladorEgresado;
import co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.controladores.ControladorOfertaLaboral;
import co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.controladores.ControladorPrograma;
import co.edu.ingesoft.proyecto.persistencia.entidades.Empresa;
import co.edu.ingesoft.proyecto.persistencia.entidades.InfoLaboralEgresado;
import co.edu.ingesoft.proyecto.persistencia.entidades.OfertaLaboral;
import co.edu.ingesoft.proyecto.persistencia.entidades.Programa;

/**
 *
 * @author TOSHIBAP55W
 */
public class VentanaOfertasPrograma extends javax.swing.JFrame {

    /**
     * Creates new form VentanaOfertasPrograma
     */
	private ControladorPrograma conProg;
	private ControladorEgresado conEgre;
	private ControladorOfertaLaboral conOfer;
	
    public VentanaOfertasPrograma() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         this.setResizable(false);
         conProg = new ControladorPrograma();
         conEgre = new ControladorEgresado();
         conOfer = new ControladorOfertaLaboral();
         
        try {
        	
			cargarComboProgramas();
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo1 = new javax.swing.JLabel();
        jLTitulo2 = new javax.swing.JLabel();
        jBInicio = new javax.swing.JButton();
        jCBProgramaAcademico = new javax.swing.JComboBox();
        jBBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ofertas por Programa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo1.setText("Programa Academico:");
        getContentPane().add(jLTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLTitulo2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo2.setText("OFERTAS POR PROGRAMA");
        getContentPane().add(jLTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jBInicio.setBackground(new java.awt.Color(255, 255, 255));
        jBInicio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jBInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-inicio.jpg"))); // NOI18N
        jBInicio.setText("INICIO");
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jBInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 140, 60));

        jCBProgramaAcademico.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jCBProgramaAcademico.setForeground(new java.awt.Color(255, 0, 0));
        jCBProgramaAcademico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Programa" }));
        getContentPane().add(jCBProgramaAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 320, 40));

        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-Buscar.png"))); // NOI18N
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 90, 60));

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Empresa", "Fecha de publicacion", "Cargo", "Salario", "Resumen"
            }
        ));
        jScrollPane2.setViewportView(jTabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 800, 180));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBInicio;
    private javax.swing.JComboBox jCBProgramaAcademico;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JLabel jLTitulo2;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
    
    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        VentanaPrincipal principal = new VentanaPrincipal(3);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBInicioActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      VentanaPrincipal principal = new VentanaPrincipal(3);
        this.dispose();
        principal.setVisible(true);
       
    }//GEN-LAST:event_formWindowClosing

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        if(jCBProgramaAcademico.getSelectedIndex()==0){
        	JOptionPane.showMessageDialog(null, "Por favr seleccione un programa academico","SELECCIONE",JOptionPane.INFORMATION_MESSAGE);
        }else{
        	try {
        	
        		Programa programa = (Programa) jCBProgramaAcademico.getSelectedItem();
        		cargarOfertasPrograma(programa);	
				
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
        	
        }
    }//GEN-LAST:event_jBBuscarActionPerformed


    public void cargarComboProgramas() throws Exception{
    	
    	List<Programa>lista = conProg.listarProgramas();
    	for (Programa programa : lista) {
			jCBProgramaAcademico.addItem(programa);
		}
    }
    
    public void cargarOfertasPrograma(Programa programa){
    	try {
    		DefaultTableModel table = (DefaultTableModel) jTabla.getModel();
    		table.setRowCount(0);
    		List<OfertaLaboral> ofertas = conOfer.buscarOfertaPorPrograma(programa);
    		if(ofertas.size() > 0){
				for (OfertaLaboral of : ofertas) {
					table.addRow(new Object[]{of.getIdEmpresa().getNombreEmpresa(),of.getAperturaOferta(),
						of.getCargo(),of.getSalario(),of.getResumen()});

				}
    		}
    		
    		
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
}
