/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.gui;

import java.util.List;

import javax.swing.JOptionPane;

import co.edu.eam.disenosoft.proyecto.logica.excepciones.ExcepcionNegocio;
import co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.controladores.ControladorAreaInteres;
import co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.controladores.ControladorContacto;
import co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.controladores.ControladorEducacionEgresado;
import co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.controladores.ControladorEgresado;
import co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.controladores.ControladorEmpresa;
import co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.controladores.ControladorFacultad;
import co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.controladores.ControladorPrograma;
import co.edu.ingesoft.proyecto.persistencia.entidades.AreaInteres;
import co.edu.ingesoft.proyecto.persistencia.entidades.Contacto;
import co.edu.ingesoft.proyecto.persistencia.entidades.EducacionEgresado;
import co.edu.ingesoft.proyecto.persistencia.entidades.Egresado;
import co.edu.ingesoft.proyecto.persistencia.entidades.Empresa;
import co.edu.ingesoft.proyecto.persistencia.entidades.Facultad;
import co.edu.ingesoft.proyecto.persistencia.entidades.InfoLaboralEgresado;
import co.edu.ingesoft.proyecto.persistencia.entidades.Programa;

/**
 *
 * @author TOSHIBAP55W
 */
public class VentanaPrincipal extends javax.swing.JFrame {

	/**
	 * Creates new form VentanaPrincipal
	 */
	private ControladorEgresado conEgre;
	private ControladorEducacionEgresado conEdueg;
	private ControladorFacultad conFac;
	private ControladorPrograma conPro;
	private ControladorAreaInteres conArea;
	private ControladorEmpresa conEmpre;
	private ControladorContacto conContac;

	public VentanaPrincipal(int posVentana) {
		initComponents();
		this.setLocationRelativeTo(null);
		this.setResizable(false);
		if (posVentana == 0) {
			jTPPrincipal.setSelectedIndex(0);
		} else if (posVentana == 1) {
			jTPPrincipal.setSelectedIndex(1);
		} else if (posVentana == 3) {
			jTPPrincipal.setSelectedIndex(3);
		}

		conEgre = new ControladorEgresado();
		conEdueg = new ControladorEducacionEgresado();
		conFac =  new ControladorFacultad();
		conPro = new ControladorPrograma();
		conArea = new ControladorAreaInteres();
		conEmpre =  new ControladorEmpresa();
		conContac = new ControladorContacto();
		
		try {
			cargarComboFacultades();
	
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLTitulo1 = new javax.swing.JLabel();
        jTPPrincipal = new javax.swing.JTabbedPane();
        jPEgresados = new javax.swing.JPanel();
        jBRegistroEgresados = new javax.swing.JButton();
        jBEdicionEgresados = new javax.swing.JButton();
        jBOfertasEgresados = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPEmpresas = new javax.swing.JPanel();
        jBRegistrarEmpresa = new javax.swing.JButton();
        jBEditarEmpresa = new javax.swing.JButton();
        jBRegistrarOferta = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPInfoParametrica = new javax.swing.JPanel();
        jTPInfoParametrica = new javax.swing.JTabbedPane();
        jPGestionFacultades = new javax.swing.JPanel();
        jBRegistrarFacultad = new javax.swing.JButton();
        jTFNombreFacultad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTFIdFacultad = new javax.swing.JTextField();
        jBEditarFacultad = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPGestionPrograma = new javax.swing.JPanel();
        jTFNombrePrograma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFIdPrograma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBRegistrarPrograma = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCBFacultad = new javax.swing.JComboBox();
        jBEditarPrograma = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPAreasInteres = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTFNombreArea = new javax.swing.JTextField();
        jBRegistrarArea = new javax.swing.JButton();
        jTFIdArea = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jBEditarArea = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBReporteEgresados = new javax.swing.JButton();
        jBOfertasAbiertas = new javax.swing.JButton();
        jBEmpleadosEmpresa = new javax.swing.JButton();
        jBReportesPrograma = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Informacion");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo1.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        jLTitulo1.setText("Sistema de información");
        getContentPane().add(jLTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jTPPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTPPrincipal.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N

        jPEgresados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBRegistroEgresados.setBackground(new java.awt.Color(255, 255, 255));
        jBRegistroEgresados.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBRegistroEgresados.setText("REGISTRAR EGRESADO");
        jBRegistroEgresados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRegistroEgresados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistroEgresadosActionPerformed(evt);
            }
        });
        jPEgresados.add(jBRegistroEgresados, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 60, 290, 49));

        jBEdicionEgresados.setBackground(new java.awt.Color(255, 255, 255));
        jBEdicionEgresados.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBEdicionEgresados.setText("BUSCAR/EDITAR EGRESADO");
        jBEdicionEgresados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEdicionEgresados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEdicionEgresadosActionPerformed(evt);
            }
        });
        jPEgresados.add(jBEdicionEgresados, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 300, 49));

        jBOfertasEgresados.setBackground(new java.awt.Color(255, 255, 255));
        jBOfertasEgresados.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBOfertasEgresados.setText("OFERTAS");
        jBOfertasEgresados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBOfertasEgresados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOfertasEgresadosActionPerformed(evt);
            }
        });
        jPEgresados.add(jBOfertasEgresados, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 230, 49));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jPEgresados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 740, 330));

        jTPPrincipal.addTab("Egresados", jPEgresados);

        jPEmpresas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBRegistrarEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        jBRegistrarEmpresa.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBRegistrarEmpresa.setText("REGISTRAR EMPRESA");
        jBRegistrarEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRegistrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarEmpresaActionPerformed(evt);
            }
        });
        jPEmpresas.add(jBRegistrarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 270, 49));

        jBEditarEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        jBEditarEmpresa.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBEditarEmpresa.setText("BUSCAR/EDITAR EMPRESA");
        jBEditarEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEditarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarEmpresaActionPerformed(evt);
            }
        });
        jPEmpresas.add(jBEditarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, 49));

        jBRegistrarOferta.setBackground(new java.awt.Color(255, 255, 255));
        jBRegistrarOferta.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBRegistrarOferta.setText("REGISTRAR OFERTA");
        jBRegistrarOferta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRegistrarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarOfertaActionPerformed(evt);
            }
        });
        jPEmpresas.add(jBRegistrarOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 270, 49));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jPEmpresas.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 740, 330));

        jTPPrincipal.addTab("Empresas", jPEmpresas);

        jPInfoParametrica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTPInfoParametrica.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jPGestionFacultades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBRegistrarFacultad.setBackground(new java.awt.Color(255, 255, 255));
        jBRegistrarFacultad.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBRegistrarFacultad.setText("REGISTRAR FACULTAD");
        jBRegistrarFacultad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRegistrarFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarFacultadActionPerformed(evt);
            }
        });
        jPGestionFacultades.add(jBRegistrarFacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 49));
        jPGestionFacultades.add(jTFNombreFacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 260, 30));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre de Facultad:");
        jPGestionFacultades.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID del Facultad:");
        jPGestionFacultades.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));
        jPGestionFacultades.add(jTFIdFacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 260, 30));

        jBEditarFacultad.setBackground(new java.awt.Color(255, 255, 255));
        jBEditarFacultad.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBEditarFacultad.setText("EDITAR FACULTAD");
        jBEditarFacultad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEditarFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarFacultadActionPerformed(evt);
            }
        });
        jPGestionFacultades.add(jBEditarFacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 240, 49));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jPGestionFacultades.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 740, 260));

        jTPInfoParametrica.addTab("Gestion de Facultades", jPGestionFacultades);

        jPGestionPrograma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPGestionPrograma.add(jTFNombrePrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 260, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione facultad:");
        jPGestionPrograma.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));
        jPGestionPrograma.add(jTFIdPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 260, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID del programa:");
        jPGestionPrograma.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jBRegistrarPrograma.setBackground(new java.awt.Color(255, 255, 255));
        jBRegistrarPrograma.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBRegistrarPrograma.setText("REGISTRAR PROGRAMA");
        jBRegistrarPrograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRegistrarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarProgramaActionPerformed(evt);
            }
        });
        jPGestionPrograma.add(jBRegistrarPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 49));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre del programa:");
        jPGestionPrograma.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPGestionPrograma.add(jCBFacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 230, 30));

        jBEditarPrograma.setBackground(new java.awt.Color(255, 255, 255));
        jBEditarPrograma.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBEditarPrograma.setText("EDITAR PROGRAMA");
        jBEditarPrograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEditarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarProgramaActionPerformed(evt);
            }
        });
        jPGestionPrograma.add(jBEditarPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 250, 49));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jPGestionPrograma.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 740, 260));

        jTPInfoParametrica.addTab("Gestion de Programa", jPGestionPrograma);

        jPAreasInteres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre de Area:");
        jPAreasInteres.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));
        jPAreasInteres.add(jTFNombreArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 260, 30));

        jBRegistrarArea.setBackground(new java.awt.Color(255, 255, 255));
        jBRegistrarArea.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBRegistrarArea.setText("REGISTRAR AREA");
        jBRegistrarArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRegistrarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarAreaActionPerformed(evt);
            }
        });
        jPAreasInteres.add(jBRegistrarArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 49));
        jPAreasInteres.add(jTFIdArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 260, 30));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ID del Area:");
        jPAreasInteres.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jBEditarArea.setBackground(new java.awt.Color(255, 255, 255));
        jBEditarArea.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBEditarArea.setText("EDITAR AREA");
        jBEditarArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEditarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarAreaActionPerformed(evt);
            }
        });
        jPAreasInteres.add(jBEditarArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 200, 49));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jPAreasInteres.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 740, 260));

        jTPInfoParametrica.addTab("Gestion Areas de Interes", jPAreasInteres);

        jPInfoParametrica.add(jTPInfoParametrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 730, 290));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jPInfoParametrica.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 740, 330));

        jTPPrincipal.addTab("Informacion Parametrica", jPInfoParametrica);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBReporteEgresados.setBackground(new java.awt.Color(255, 255, 255));
        jBReporteEgresados.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBReporteEgresados.setText("REPORTE DE EGRESADOS");
        jBReporteEgresados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBReporteEgresados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReporteEgresadosActionPerformed(evt);
            }
        });
        jPanel1.add(jBReporteEgresados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 49));

        jBOfertasAbiertas.setBackground(new java.awt.Color(255, 255, 255));
        jBOfertasAbiertas.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBOfertasAbiertas.setText("OFERTAS ABIERTAS");
        jBOfertasAbiertas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBOfertasAbiertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOfertasAbiertasActionPerformed(evt);
            }
        });
        jPanel1.add(jBOfertasAbiertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 260, 49));

        jBEmpleadosEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        jBEmpleadosEmpresa.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBEmpleadosEmpresa.setText("EMPLEADOS POR EMPRESA");
        jBEmpleadosEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEmpleadosEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpleadosEmpresaActionPerformed(evt);
            }
        });
        jPanel1.add(jBEmpleadosEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 49));

        jBReportesPrograma.setBackground(new java.awt.Color(255, 255, 255));
        jBReportesPrograma.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jBReportesPrograma.setText("REPORTES POR PROGRAMA");
        jBReportesPrograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBReportesPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReportesProgramaActionPerformed(evt);
            }
        });
        jPanel1.add(jBReportesPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, 49));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 740, 330));

        jTPPrincipal.addTab("Reportes y Estadisticas", jPanel1);

        getContentPane().add(jTPPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 740, 360));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 950, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEdicionEgresados;
    private javax.swing.JButton jBEditarArea;
    private javax.swing.JButton jBEditarEmpresa;
    private javax.swing.JButton jBEditarFacultad;
    private javax.swing.JButton jBEditarPrograma;
    private javax.swing.JButton jBEmpleadosEmpresa;
    private javax.swing.JButton jBOfertasAbiertas;
    private javax.swing.JButton jBOfertasEgresados;
    private javax.swing.JButton jBRegistrarArea;
    private javax.swing.JButton jBRegistrarEmpresa;
    private javax.swing.JButton jBRegistrarFacultad;
    private javax.swing.JButton jBRegistrarOferta;
    private javax.swing.JButton jBRegistrarPrograma;
    private javax.swing.JButton jBRegistroEgresados;
    private javax.swing.JButton jBReporteEgresados;
    private javax.swing.JButton jBReportesPrograma;
    private javax.swing.JComboBox jCBFacultad;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPAreasInteres;
    private javax.swing.JPanel jPEgresados;
    private javax.swing.JPanel jPEmpresas;
    private javax.swing.JPanel jPGestionFacultades;
    private javax.swing.JPanel jPGestionPrograma;
    private javax.swing.JPanel jPInfoParametrica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFIdArea;
    private javax.swing.JTextField jTFIdFacultad;
    private javax.swing.JTextField jTFIdPrograma;
    private javax.swing.JTextField jTFNombreArea;
    private javax.swing.JTextField jTFNombreFacultad;
    private javax.swing.JTextField jTFNombrePrograma;
    private javax.swing.JTabbedPane jTPInfoParametrica;
    private javax.swing.JTabbedPane jTPPrincipal;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
	
	private void jBRegistroEgresadosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBRegistroEgresadosActionPerformed
		int tipo = 0;
		VentanaEgresados egresados = new VentanaEgresados(null,tipo,null,null);
		egresados.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jBRegistroEgresadosActionPerformed

	private void jBEdicionEgresadosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEdicionEgresadosActionPerformed
		String ced = JOptionPane.showInputDialog(null, "Ingrese la cedula del egresado que desea buscar/editar ","INGRESE",JOptionPane.INFORMATION_MESSAGE);

		if (ced!=null) {
			try {
				
				int cedula = Integer.parseInt(ced);
				Egresado eg = conEgre.buscarEgresado(cedula);
				EducacionEgresado eduEgre = conEdueg.buscarEducacion(cedula);
				InfoLaboralEgresado inf = conEgre.buscarInfoLaboral(cedula);
			 if(eg!=null){
				 	int tipo = 1;
				     VentanaEgresados egresados = new VentanaEgresados(eg,tipo,eduEgre,inf);
				     egresados.setVisible(true);
				     this.dispose();
			 
			}
			}catch (ExcepcionNegocio ex){
				JOptionPane.showMessageDialog(null, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
			}catch (NumberFormatException exe){
				JOptionPane.showMessageDialog(null, "Digite identificacion y verifique que solo tenga valores numericos","ERROR",JOptionPane.ERROR_MESSAGE);
			}catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		
		}
	}// GEN-LAST:event_jBEdicionEgresadosActionPerformed

	private void jBRegistrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBRegistrarEmpresaActionPerformed
		int tipo = 0;
		VentanaEmpresa empresa = new VentanaEmpresa(null,tipo,null);
		empresa.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jBRegistrarEmpresaActionPerformed

	private void jBEditarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEditarEmpresaActionPerformed
		String nit = JOptionPane.showInputDialog(null, "Ingrese el NIT de la empresa que desea buscar/editar ");
		if (nit != null) {
			try{
			int nitEm = Integer.parseInt(nit);
			Empresa emp = conEmpre.buscarEmpresa(nitEm);
			Contacto cont = conContac.buscarContacto(emp.getNit());
			
			if(emp!=null){
				int tipo=1;
				VentanaEmpresa empresa = new VentanaEmpresa(emp,tipo,cont);
				empresa.setVisible(true);
				this.dispose();
			}
			
			}catch (ExcepcionNegocio ex){
				JOptionPane.showMessageDialog(null, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
			}catch (NumberFormatException exe){
				JOptionPane.showMessageDialog(null, "Digite el NIT de la empresa y verifique que solo tenga valores numericos","ERROR",JOptionPane.ERROR_MESSAGE);
			}catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		
		}
	}// GEN-LAST:event_jBEditarEmpresaActionPerformed

	private void jBOfertasEgresadosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBOfertasEgresadosActionPerformed
		VentanaOfertasEgresados ofertas = new VentanaOfertasEgresados();
		ofertas.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jBOfertasEgresadosActionPerformed

	private void jBReporteEgresadosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBReporteEgresadosActionPerformed
		VentanaReporteEgresados reporteEgresados = new VentanaReporteEgresados();
		reporteEgresados.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jBReporteEgresadosActionPerformed

	private void jBOfertasAbiertasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBOfertasAbiertasActionPerformed
		VentanaOfertasAbiertas ofertas = new VentanaOfertasAbiertas();
		ofertas.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jBOfertasAbiertasActionPerformed

	private void jBEmpleadosEmpresaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpleadosEmpresaActionPerformed
		VentanaEmpleadosEmpresa empleadosEmp = new VentanaEmpleadosEmpresa();
		empleadosEmp.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jBEmpleadosEmpresaActionPerformed

	private void jBReportesProgramaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBReportesProgramaActionPerformed
		VentanaReporteEgresados reporEgre = new VentanaReporteEgresados();
		reporEgre.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jBReportesProgramaActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				// new VentanaPrincipal().setVisible(true);\
				new VentanaPrincipal(0).setVisible(true);
			}
		});
	}
	public void cargarComboFacultades() throws Exception {

		jCBFacultad.removeAllItems();
		List<Facultad> lista = conFac.listarFacultades();
		for (int i = 0; i < lista.size(); i++) {
			jCBFacultad.addItem(lista.get(i));
		}
	}

	 private void jBRegistrarFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarFacultadActionPerformed
		 try {
		  int idFacultad = Integer.parseInt(jTFIdFacultad.getText());
	       String nombreFac = jTFNombreFacultad.getText();
	       
	       if(jTFIdFacultad.getText().isEmpty()||jTFNombreFacultad.getText().isEmpty()){
	    	   JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos","INGRESE",JOptionPane.ERROR_MESSAGE); 
	       }else{
	      Facultad facultad = new Facultad(idFacultad, nombreFac);
	      Facultad fac= conFac.buscarFacultad(idFacultad);
	      
	       if(fac!=null){
	    	   JOptionPane.showMessageDialog(null,"La facultad con ID ''"+idFacultad+"'' ya se encuentra registrada","ERROR",JOptionPane.ERROR_MESSAGE);
	       }else{
			conFac.registrarFacultad(facultad);
			JOptionPane.showMessageDialog(null,"Se ha registrado exitosamente","EXITO",JOptionPane.INFORMATION_MESSAGE);
			cargarComboFacultades();
	       }
	       }
		}catch (ExcepcionNegocio ex){
			JOptionPane.showMessageDialog(null, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
		}catch (NumberFormatException exe){
			JOptionPane.showMessageDialog(null, "Digite el ID de facultad y verifique que solo tenga valores numericos","ERROR",JOptionPane.WARNING_MESSAGE);
		}catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    }//GEN-LAST:event_jBRegistrarFacultadActionPerformed

	    private void jBRegistrarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarProgramaActionPerformed
	    	 try {
	    int idPrograma = Integer.parseInt(jTFIdPrograma.getText());
	      Facultad idFacultad = (Facultad)jCBFacultad.getSelectedItem();
	      String nombrePro = jTFNombrePrograma.getText();
	      
	      if(jTFIdPrograma.getText().isEmpty()||jTFNombrePrograma.getText().isEmpty()){
	    	   JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos","INGRESE",JOptionPane.ERROR_MESSAGE); 
	      }else{
	      Programa programa = new Programa(idFacultad, idPrograma, nombrePro);
	      Programa pro = conPro.buscarPrograma(idPrograma);
	      if(pro!=null){
	    	   JOptionPane.showMessageDialog(null,"El programa con ID ''"+idPrograma+"'' ya se encuentra registrado","ERROR",JOptionPane.ERROR_MESSAGE);
	      }else{
	    	  conPro.registrarPrograma(programa);
	    	  JOptionPane.showMessageDialog(null,"Se ha registrado exitosamente","EXITO",JOptionPane.INFORMATION_MESSAGE);
	      }
	      }
	      
	    }catch (ExcepcionNegocio ex){
			JOptionPane.showMessageDialog(null, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
		}catch (NumberFormatException exe){
			JOptionPane.showMessageDialog(null, "Digite el ID del programa y verifique que solo tenga valores numericos","ERROR",JOptionPane.WARNING_MESSAGE);
		}catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    }//GEN-LAST:event_jBRegistrarProgramaActionPerformed

	    private void jBRegistrarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarAreaActionPerformed
	    	try {
	    		
	    		int idArea = Integer.parseInt(jTFIdArea.getText());
	    		String nombreArea = jTFNombreArea.getText();
	    		if(jTFIdArea.getText().isEmpty()||jTFNombreArea.getText().isEmpty()){
	    			JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos","INGRESE",JOptionPane.ERROR_MESSAGE); 
	    		}else{
	    			AreaInteres area = new AreaInteres(idArea, nombreArea);
	    			conArea.registrarAreaInteres(area);
	    			JOptionPane.showMessageDialog(null,"Se ha registrado exitosamente","EXITO",JOptionPane.INFORMATION_MESSAGE);
	    		}
	    	}catch (ExcepcionNegocio ex){
				JOptionPane.showMessageDialog(null, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
			}catch (NumberFormatException exe){
				JOptionPane.showMessageDialog(null, "Digite el ID del area de interes y verifique que solo tenga valores numericos","ERROR",JOptionPane.WARNING_MESSAGE);
			}catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	    }//GEN-LAST:event_jBRegistrarAreaActionPerformed

    private void jBEditarFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarFacultadActionPerformed
       
        if(jTFIdFacultad.getText().isEmpty()){
        	JOptionPane.showMessageDialog(null, "Por favor ingrese el ID de la facultad para poder editarla","ERROR",JOptionPane.WARNING_MESSAGE);
        }else{
        	try{
        		if(jTFNombreFacultad.getText().isEmpty()){
                	JOptionPane.showMessageDialog(null, "Por favor ingrese el nombre de la facultad que desea editar","ERROR",JOptionPane.WARNING_MESSAGE);
                	return;
        		}
        	int idFacultad= Integer.parseInt(jTFIdFacultad.getText());
        	String nombreFac = jTFNombreFacultad.getText();
        	Facultad fac = conFac.buscarFacultad(idFacultad);
        	if(fac!=null){
        	jTFNombreFacultad.setText(fac.getNombreFacultad());
        	Facultad facu = new Facultad(idFacultad, nombreFac);
        	conFac.editarFacultad(facu);
        	JOptionPane.showMessageDialog(null,"Se ha editado exitosamente","EXITO",JOptionPane.INFORMATION_MESSAGE);
        	}else{
        		JOptionPane.showMessageDialog(null, 
        				"La facultad con ID  ''"+idFacultad+"'' (No) se encuentra registrada","ERROR",JOptionPane.ERROR_MESSAGE);
        	}
        	
        	}catch (ExcepcionNegocio ex){
				JOptionPane.showMessageDialog(null, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
			}catch (NumberFormatException exe){
				JOptionPane.showMessageDialog(null, "Digite el ID del area de interes y verifique que solo tenga valores numericos","ERROR",JOptionPane.WARNING_MESSAGE);
			}catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
        }
    }//GEN-LAST:event_jBEditarFacultadActionPerformed

    private void jBEditarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarProgramaActionPerformed
        
    	if(jTFIdPrograma.getText().isEmpty()){
        	JOptionPane.showMessageDialog(null, "Por favor ingrese el ID del programa para poder editarlo","ERROR",JOptionPane.WARNING_MESSAGE);
    	}else{
    		
    		try{
    			if(jTFNombrePrograma.getText().isEmpty()){
    	        	JOptionPane.showMessageDialog(null, "Por favor ingrese el nombre del programa que desea editar","ERROR",JOptionPane.WARNING_MESSAGE);
    	        	return;
    			}
    			
            	int idPrograma= Integer.parseInt(jTFIdPrograma.getText());
            	Facultad idFacultad = (Facultad)jCBFacultad.getSelectedItem();
            	String nombrePro = jTFNombrePrograma.getText();
            	Programa programa = new Programa(idFacultad, idPrograma, nombrePro) ;
            	conPro.editarPrograma(programa);
            	JOptionPane.showMessageDialog(null,"Se ha editado exitosamente","EXITO",JOptionPane.INFORMATION_MESSAGE);
            	
            	}catch (ExcepcionNegocio ex){
    				JOptionPane.showMessageDialog(null, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
    			}catch (NumberFormatException exe){
    				JOptionPane.showMessageDialog(null, "Digite el ID del area de interes y verifique que solo tenga valores numericos","ERROR",JOptionPane.WARNING_MESSAGE);
    			}catch (Exception e) {
    				// TODO Auto-generated catch block
    				e.printStackTrace();
    			}
    	}
    		
    	
    }//GEN-LAST:event_jBEditarProgramaActionPerformed

    private void jBEditarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarAreaActionPerformed
       
    	if(jTFIdArea.getText().isEmpty()){
        	JOptionPane.showMessageDialog(null, "Por favor ingrese el ID del area para poder editarla","ERROR",JOptionPane.WARNING_MESSAGE);
    	}else{
    		
    		try{
            	if(jTFNombreArea.getText().isEmpty()){
                	JOptionPane.showMessageDialog(null, "Por favor ingrese el nombre del area que desea editar","ERROR",JOptionPane.WARNING_MESSAGE);
                	return;
            	}
    			int idArea= Integer.parseInt(jTFIdArea.getText());
            	String nombreArea = jTFNombreArea.getText();
            	AreaInteres area = new AreaInteres(idArea, nombreArea);
            	conArea.editarAreaInteres(area);

            	
            	}catch (ExcepcionNegocio ex){
    				JOptionPane.showMessageDialog(null, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
    			}catch (NumberFormatException exe){
    				JOptionPane.showMessageDialog(null, "Digite el ID del area de interes y verifique que solo tenga valores numericos","ERROR",JOptionPane.WARNING_MESSAGE);
    			}catch (Exception e) {
    				// TODO Auto-generated catch block
    				e.printStackTrace();
    			}
    	}
    }//GEN-LAST:event_jBEditarAreaActionPerformed

    private void jBRegistrarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarOfertaActionPerformed
      
        VentanaOfertasEmpresa ofertasEmp = new VentanaOfertasEmpresa();
		ofertasEmp.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_jBRegistrarOfertaActionPerformed

    
    
}
