/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingsoft.desarrollo.proyecto_final.vista.gui;

/**
 *
 * @author TOSHIBAP55W
 */
public class VentanaOfertasEgresados extends javax.swing.JFrame {

    /**
     * Creates new form VentanaOfertasEgresados
     */
    public VentanaOfertasEgresados() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         this.setResizable(false);
         jPanelDatos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo1 = new javax.swing.JLabel();
        jLTitulo2 = new javax.swing.JLabel();
        jBInicio = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jPanelDatos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTADescripcionOfert = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTARequerimientosOfert = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAResumenOfert = new javax.swing.JTextArea();
        jTFSalarioOfert = new javax.swing.JTextField();
        jTFCiudadOfert = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTFAreaConocimientoOfert = new javax.swing.JTextField();
        jTFCargoOfert = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel28 = new javax.swing.JLabel();
        jTFIDEgresado = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTFProgramaOfrecer = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTFEmpresaOfrecer = new javax.swing.JTextField();
        jBAplicarOferta = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jBVerOferta = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ofertas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo1.setText("OFERTAS LABORALES");
        getContentPane().add(jLTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jLTitulo2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo2.setText("Ofertas:");
        getContentPane().add(jLTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jBInicio.setBackground(new java.awt.Color(255, 255, 255));
        jBInicio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jBInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-inicio.jpg"))); // NOI18N
        jBInicio.setText("INICIO");
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jBInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 140, 60));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 350, 40));

        jPanelDatos.setBackground(new java.awt.Color(204, 204, 204));
        jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTADescripcionOfert.setColumns(20);
        jTADescripcionOfert.setRows(5);
        jScrollPane4.setViewportView(jTADescripcionOfert);

        jPanelDatos.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 310, 160));

        jTARequerimientosOfert.setColumns(20);
        jTARequerimientosOfert.setRows(5);
        jScrollPane2.setViewportView(jTARequerimientosOfert);

        jPanelDatos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 310, 110));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Descripcion de la Oferta:");
        jPanelDatos.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Resumen:");
        jPanelDatos.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        jTAResumenOfert.setColumns(20);
        jTAResumenOfert.setRows(5);
        jScrollPane3.setViewportView(jTAResumenOfert);

        jPanelDatos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 310, 160));
        jPanelDatos.add(jTFSalarioOfert, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 310, 40));
        jPanelDatos.add(jTFCiudadOfert, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 310, 40));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Ciudad de la oferta:");
        jPanelDatos.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, -1, -1));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Empresa que oferta:");
        jPanelDatos.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));
        jPanelDatos.add(jTFAreaConocimientoOfert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 310, 40));
        jPanelDatos.add(jTFCargoOfert, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 310, 40));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Apertura de la oferta:");
        jPanelDatos.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, -1, -1));
        jPanelDatos.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 300, -1));

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Ingrese ID para aplicar oferta:");
        jPanelDatos.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanelDatos.add(jTFIDEgresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, 40));

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Para el Programa:");
        jPanelDatos.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Cargo a Ofrecer:");
        jPanelDatos.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));
        jPanelDatos.add(jTFProgramaOfrecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 202, 300, 40));

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Area de Conocimiento:");
        jPanelDatos.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));
        jPanelDatos.add(jTFEmpresaOfrecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 300, 40));

        jBAplicarOferta.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jBAplicarOferta.setForeground(new java.awt.Color(255, 0, 0));
        jBAplicarOferta.setText("APLICAR OFERTA");
        jBAplicarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAplicarOfertaActionPerformed(evt);
            }
        });
        jPanelDatos.add(jBAplicarOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 650, 270, 40));

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Requerimientos de la oferta:");
        jPanelDatos.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Salario a ofrecer:");
        jPanelDatos.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanelDatos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 710));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanelDatos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 1150, 840));

        getContentPane().add(jPanelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1150, 710));

        jBVerOferta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-Buscar.png"))); // NOI18N
        jBVerOferta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBVerOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerOfertaActionPerformed(evt);
            }
        });
        getContentPane().add(jBVerOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 80, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAplicarOferta;
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jBVerOferta;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JLabel jLTitulo2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTADescripcionOfert;
    private javax.swing.JTextArea jTARequerimientosOfert;
    private javax.swing.JTextArea jTAResumenOfert;
    private javax.swing.JTextField jTFAreaConocimientoOfert;
    private javax.swing.JTextField jTFCargoOfert;
    private javax.swing.JTextField jTFCiudadOfert;
    private javax.swing.JTextField jTFEmpresaOfrecer;
    private javax.swing.JTextField jTFIDEgresado;
    private javax.swing.JTextField jTFProgramaOfrecer;
    private javax.swing.JTextField jTFSalarioOfert;
    // End of variables declaration//GEN-END:variables
    
    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        VentanaPrincipal principal = new VentanaPrincipal(0);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBInicioActionPerformed

    private void jBAplicarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAplicarOfertaActionPerformed
        VentanaPrincipal principal = new VentanaPrincipal(0);
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBAplicarOfertaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        VentanaPrincipal principal = new VentanaPrincipal(0);
        this.dispose();
        principal.setVisible(true);
       
    }//GEN-LAST:event_formWindowClosing

    private void jBVerOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerOfertaActionPerformed
       jPanelDatos.setVisible(true);
    }//GEN-LAST:event_jBVerOfertaActionPerformed

   

    
}
